stages:
  - containerization
  - deployment

variables:
  APPLICATION_NAME: image-storage-front-vuetify
  SERVICE_PORT: 31228

containerization:
  stage: containerization
  tags:
    - "x86"
  script:
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}

deployment:
  stage: deployment
  tags:
    - kubectl
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment ${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
