stages:
  - build

services:
  - name: docker:19.03.12-dind

variables:
  APPLICATION_NAME: image-storage-service-gui
  CONTAINER_IMAGE: ${AWS_ECR_PUBLIC_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}


build:
  stage: build
  only:
    - master
    - mongoose
  tags:
    - dind
  before_script:
    # Registry login
    - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${AWS_ECR_PUBLIC_URL}
  script:
    # Building image
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging images
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}

    # Pushing images
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}

# TODO: Build aarch64