
stages:
  - build
  - build-aarch64

variables:
  APPLICATION_NAME: image-storage-front-vuetify
  SERVICE_PORT: 31228
  CONTAINER_TAG: ${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CONTAINER_TAG}
  CONTAINER_IMAGE_DOCKER_HUB: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  CONTAINER_IMAGE_DOCKER_HUB_TAGGED: ${CONTAINER_IMAGE_DOCKER_HUB}:${CONTAINER_TAG}

build:
  stage: build
  tags:
    - "x86"
  before_script:
    - >
      echo "${DOCKER_HUB_PASSWORD}"
      | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    # Building image
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging image
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DOCKER_HUB}
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DOCKER_HUB_TAGGED}
    # Pushing images
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}
    - docker push ${CONTAINER_IMAGE_DOCKER_HUB}
    - docker push ${CONTAINER_IMAGE_DOCKER_HUB_TAGGED}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE_TAGGED}
    - docker image rm ${CONTAINER_IMAGE_DOCKER_HUB}
    - docker image rm ${CONTAINER_IMAGE_DOCKER_HUB_TAGGED}

build-aarch64:
  stage: build-aarch64
  tags:
    - "aarch64"
  script:
    - >
      docker build
      --build-arg HTTP_PROXY=http://172.16.98.151:8118
      --build-arg HTTPS_PROXY=http://172.16.98.151:8118
      -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64 .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64
