stages:
  - containerization
  - containerization-aarch64
  - deployment

variables:
  APPLICATION_NAME: image-storage-front-vuetify
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_DOCKER_HUB: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  SERVICE_PORT: 31228

containerization:
  stage: containerization
  tags:
    - "x86"
  script:
    - > echo "${DOCKER_HUB_PASSWORD}"
    | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin ;
    # Building image
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging image for Docker Hub
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DOCKER_HUB}
    # Pushing images
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_DOCKER_HUB}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE_DOCKER_HUB}

containerization-aarch64:
  stage: containerization-aarch64
  tags:
    - "aarch64"
  script:
    - >
      docker build
      --build-arg HTTP_PROXY=http://172.16.98.151:8118
      --build-arg HTTPS_PROXY=http://172.16.98.151:8118
      -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64 .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64

# Deployment to seikai's DB server
deployment:
  stage: deployment
  tags:
    - kubectl
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment ${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
