stages:
  - build

variables:
  APPLICATION_NAME: image-storage-mongoose-front
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  CONTAINER_IMAGE_DOCKER_HUB: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}

build-x86:
  stage: build
  tags:
    - "x86"
  script:
    - >
      echo "${DOCKER_HUB_PASSWORD}"
      | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building image
    - docker build -t ${CONTAINER_IMAGE} .
    # Tagging image for Docker Hub
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_DOCKER_HUB}
    # Pushing images
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_DOCKER_HUB}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}
    - docker image rm ${CONTAINER_IMAGE_DOCKER_HUB}

build-aarch64:
  stage: build
  tags:
    - "aarch64"
  script:
    - >
      docker build
      --build-arg HTTP_PROXY=http://172.16.98.151:8118
      --build-arg HTTPS_PROXY=http://172.16.98.151:8118
      -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64 .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64
