stages:
  - containerization
  - containerization-aarch64
  - deployment

variables:
  APPLICATION_NAME: image-storage-front-vuetify
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
  SERVICE_PORT: 31228

containerization:
  stage: containerization
  tags:
    - "x86"
  script:
    - echo ${DOCKER_HUB_USERNAME}
    - >
     if [ -z ${DOCKER_HUB_USERNAME} ];
     then echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin ;
     else echo "No Docker login" -;
     fi
    - docker build -t ${CONTAINER_IMAGE} .
    - docker push ${CONTAINER_IMAGE}
    # Cleanup
    - docker image rm ${CONTAINER_IMAGE}

containerization-aarch64:
  stage: containerization-aarch64
  tags:
    - "aarch64"
  script:
    - >
      docker build
      --build-arg HTTP_PROXY=http://172.16.98.151:8118
      --build-arg HTTPS_PROXY=http://172.16.98.151:8118
      -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64 .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}-aarch64

# Deployment to seikai's DB server
deployment:
  stage: deployment
  tags:
    - kubectl
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
    - kubectl rollout restart deployment ${APPLICATION_NAME}
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE} # Obtained from GitLab
