apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
        imagePullPolicy: Always
        env:
        - name: VUE_APP_STORAGE_SERVICVE_API_URL
          value: "http://172.16.98.151:31221"
        - name: VUE_APP_HOMEPAGE_URL
          value: "http://172.16.98.151:31226"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
  - port: 80
    nodePort: 31222
  selector:
    app: ${APPLICATION_NAME}
  type: NodePort
