FROM node:16 as build-stage

ENV HTTPS_PROXY="http://172.16.98.151:8118"
ENV HTTP_PROXY="http://172.16.98.151:8118"

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY ./ .
RUN npm run build


FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /app
COPY nginx.conf /etc/nginx/nginx.conf

# Loading environment variables atg runtime
COPY ./entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
