FROM node:16 as build-stage

ENV HTTPS_PROXY="http://172.16.98.151:8118"
ENV HTTP_PROXY="http://172.16.98.151:8118"

WORKDIR /app
COPY package*.json ./

RUN npm install
COPY ./ .
RUN npm run build

FROM nginx AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
COPY default.conf /etc/nginx/conf.d/default.conf

# Generates /usr/share/nginx/html/env.js from VITE_* env vars before nginx starts
COPY ./40-env-config.sh /docker-entrypoint.d/40-env-config.sh
RUN chmod +x /docker-entrypoint.d/40-env-config.sh
