/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/app/AppFooter.vue')['default']
    AppHeader: typeof import('./components/app/AppHeader.vue')['default']
    CustomHeader: typeof import('./components/CustomHeader.vue')['default']
    DatePicker: typeof import('./components/advancedSearch/DatePicker.vue')['default']
    DeleteDialog: typeof import('./components/DeleteDialog.vue')['default']
    ExportButton: typeof import('./components/ExportButton.vue')['default']
    FilterGroup: typeof import('./components/advancedSearch/FilterGroup.vue')['default']
    Folder: typeof import('./components/Folder.vue')['default']
    FolderImagePreview: typeof import('./components/FolderImagePreview.vue')['default']
    ImageDataEditor: typeof import('./components/ImageDataEditor.vue')['default']
    ImageDataField: typeof import('./components/ImageDataField.vue')['default']
    ImportDialog: typeof import('./components/ImportDialog.vue')['default']
    LocaleSelector: typeof import('./components/LocaleSelector.vue')['default']
    NavCategories: typeof import('./components/NavCategories.vue')['default']
    QueryParameters: typeof import('./components/advancedSearch/QueryParameters.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UpdateDialog: typeof import('./components/UpdateDialog.vue')['default']
    UploadDialog: typeof import('./components/UploadDialog.vue')['default']
  }
}
